all:
	g++ -Wall -o learnAdd learnAdd.cpp -lneural++
	g++ -Wall -o doAnd doAnd.cpp -lneural++
	g++ -Wall -o doAdd doAdd.cpp -lneural++
	g++ -Wall -o adderFromScratch adderFromScratch.cpp -lneural++

clean:
	rm learnAdd
	rm doAdd
	rm adderFromScratch
	rm adder.net
	rm adder.xml
