Neural++: CMarkup Class Reference
CMarkup Class Reference
#include <Markup.h>
Public Types
enum MarkupDocFlags {
MDF_UTF16LEFILE = 1, MDF_UTF8PREAMBLE = 4, MDF_IGNORECASE = 8, MDF_READFILE = 16,
MDF_WRITEFILE = 32, MDF_APPENDFILE = 64, MDF_UTF16BEFILE = 128
}
enum MarkupNodeFlags {
MNF_WITHCDATA = 0x01, MNF_WITHNOLINES = 0x02, MNF_WITHXHTMLSPACE = 0x04, MNF_WITHREFS = 0x08,
MNF_WITHNOEND = 0x10, MNF_ESCAPEQUOTES = 0x100, MNF_NONENDED = 0x100000, MNF_ILLDATA = 0x200000
}
enum MarkupNodeType {
MNT_ELEMENT = 1, MNT_TEXT = 2, MNT_WHITESPACE = 4, MNT_CDATA_SECTION = 8,
MNT_PROCESSING_INSTRUCTION = 16, MNT_COMMENT = 32, MNT_DOCUMENT_TYPE = 64, MNT_EXCLUDE_WHITESPACE = 123,
MNT_LONE_END_TAG = 128, MNT_NODE_ERROR = 32768
}
Public Member Functions
CMarkup ()
CMarkup (MCD_CSTR szDoc)
CMarkup (int nFlags)
CMarkup (const CMarkup &markup)
void operator= (const CMarkup &markup)
~CMarkup ()
bool Load (MCD_CSTR_FILENAME szFileName)
bool SetDoc (MCD_PCSZ pDoc)
bool SetDoc (const MCD_STR &strDoc)
bool IsWellFormed ()
bool FindElem (MCD_CSTR szName=NULL)
bool FindChildElem (MCD_CSTR szName=NULL)
bool IntoElem ()
bool OutOfElem ()
void ResetChildPos ()
void ResetMainPos ()
void ResetPos ()
MCD_STR GetTagName () const
MCD_STR GetChildTagName () const
MCD_STR GetData () const
MCD_STR GetChildData () const
MCD_STR GetElemContent () const
MCD_STR GetAttrib (MCD_CSTR szAttrib) const
MCD_STR GetChildAttrib (MCD_CSTR szAttrib) const
MCD_STR GetAttribName (int n) const
int FindNode (int nType=0)
int GetNodeType ()
bool SavePos (MCD_CSTR szPosName=MCD_T(""), int nMap=0)
bool RestorePos (MCD_CSTR szPosName=MCD_T(""), int nMap=0)
bool SetMapSize (int nSize, int nMap=0)
const MCD_STR & GetError () const
int GetDocFlags () const
void SetDocFlags (int nFlags)
bool Save (MCD_CSTR_FILENAME szFileName)
const MCD_STR & GetDoc () const
bool AddElem (MCD_CSTR szName, MCD_CSTR szData=NULL, int nFlags=0)
bool InsertElem (MCD_CSTR szName, MCD_CSTR szData=NULL, int nFlags=0)
bool AddChildElem (MCD_CSTR szName, MCD_CSTR szData=NULL, int nFlags=0)
bool InsertChildElem (MCD_CSTR szName, MCD_CSTR szData=NULL, int nFlags=0)
bool AddElem (MCD_CSTR szName, int nValue, int nFlags=0)
bool InsertElem (MCD_CSTR szName, int nValue, int nFlags=0)
bool AddChildElem (MCD_CSTR szName, int nValue, int nFlags=0)
bool InsertChildElem (MCD_CSTR szName, int nValue, int nFlags=0)
bool AddAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue)
bool AddChildAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue)
bool AddAttrib (MCD_CSTR szAttrib, int nValue)
bool AddChildAttrib (MCD_CSTR szAttrib, int nValue)
bool AddSubDoc (MCD_CSTR szSubDoc)
bool InsertSubDoc (MCD_CSTR szSubDoc)
MCD_STR GetSubDoc () const
bool AddChildSubDoc (MCD_CSTR szSubDoc)
bool InsertChildSubDoc (MCD_CSTR szSubDoc)
MCD_STR GetChildSubDoc () const
bool AddNode (int nType, MCD_CSTR szText)
bool InsertNode (int nType, MCD_CSTR szText)
bool RemoveElem ()
bool RemoveChildElem ()
bool RemoveNode ()
bool SetAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue, int nFlags=0)
bool SetChildAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue, int nFlags=0)
bool SetAttrib (MCD_CSTR szAttrib, int nValue, int nFlags=0)
bool SetChildAttrib (MCD_CSTR szAttrib, int nValue, int nFlags=0)
bool SetData (MCD_CSTR szData, int nFlags=0)
bool SetChildData (MCD_CSTR szData, int nFlags=0)
bool SetData (int nValue)
bool SetChildData (int nValue)
bool SetElemContent (MCD_CSTR szContent)
Static Public Member Functions
static bool ReadTextFile (MCD_CSTR_FILENAME szFileName, MCD_STR &strDoc, MCD_STR *pstrError=NULL, int *pnDocFlags=NULL, MCD_STR *pstrEncoding=NULL)
static bool WriteTextFile (MCD_CSTR_FILENAME szFileName, const MCD_STR &strDoc, MCD_STR *pstrError=NULL, int *pnDocFlags=NULL, MCD_STR *pstrEncoding=NULL)
static MCD_STR EscapeText (MCD_CSTR szText, int nFlags=0)
static MCD_STR UnescapeText (MCD_CSTR szText, int nTextLength=-1)
static int UTF16To8 (char *pszUTF8, const unsigned short *pwszUTF16, int nUTF8Count)
static int UTF8To16 (unsigned short *pwszUTF16, const char *pszUTF8, int nUTF8Count)
static MCD_STR UTF8ToA (MCD_CSTR pszUTF8, int *pnFailed=NULL)
static MCD_STR AToUTF8 (MCD_CSTR pszANSI)
static void EncodeCharUTF8 (int nUChar, char *pszUTF8, int &nUTF8Len)
static int DecodeCharUTF8 (const char *&pszUTF8, const char *pszUTF8End=NULL)
static void EncodeCharUTF16 (int nUChar, unsigned short *pwszUTF16, int &nUTF16Len)
static int DecodeCharUTF16 (const unsigned short *&pwszUTF16, const unsigned short *pszUTF16End=NULL)
static bool DetectUTF8 (const char *pText, int nTextLen, int *pnNonASCII=NULL)
static MCD_STR GetDeclaredEncoding (MCD_CSTR szDoc)
Protected Types
enum MarkupNodeFlagsInternal {
MNF_REPLACE = 0x001000, MNF_INSERT = 0x002000, MNF_CHILD = 0x004000, MNF_QUOTED = 0x008000,
MNF_EMPTY = 0x010000, MNF_DELETED = 0x020000, MNF_FIRST = 0x080000, MNF_PUBLIC = 0x300000,
MNF_ILLFORMED = 0x800000, MNF_USER = 0xf000000
}
Protected Member Functions
void x_SetPos (int iPosParent, int iPos, int iPosChild)
int x_GetFreePos ()
bool x_AllocPosArray (int nNewSize=0)
void InitDocFlags ()
bool x_ParseDoc ()
int x_ParseElem (int iPos, TokenPos &token)
int x_FindElem (int iPosParent, int iPos, MCD_PCSZ szPath) const
MCD_STR x_GetPath (int iPos) const
MCD_STR x_GetTagName (int iPos) const
MCD_STR x_GetData (int iPos) const
MCD_STR x_GetAttrib (int iPos, MCD_PCSZ pAttrib) const
bool x_AddElem (MCD_PCSZ pName, MCD_PCSZ pValue, int nFlags)
bool x_AddElem (MCD_PCSZ pName, int nValue, int nFlags)
MCD_STR x_GetSubDoc (int iPos) const
bool x_AddSubDoc (MCD_PCSZ pSubDoc, int nFlags)
bool x_SetAttrib (int iPos, MCD_PCSZ pAttrib, MCD_PCSZ pValue, int nFlags=0)
bool x_SetAttrib (int iPos, MCD_PCSZ pAttrib, int nValue, int nFlags=0)
bool x_AddNode (int nNodeType, MCD_PCSZ pText, int nNodeFlags)
void x_RemoveNode (int iPosParent, int &iPos, int &nNodeType, int &nNodeOffset, int &nNodeLength)
void x_AdjustForNode (int iPosParent, int iPos, int nShift)
int x_InsertNew (int iPosParent, int &iPosRel, NodePos &node)
void x_LinkElem (int iPosParent, int iPosBefore, int iPos)
int x_UnlinkElem (int iPos)
int x_ReleaseSubDoc (int iPos)
int x_ReleasePos (int iPos)
bool x_GetMap (SavedPosMap *&pMap, int nMap, int nMapSize=7)
void x_CheckSavedPos ()
bool x_SetData (int iPos, MCD_PCSZ szData, int nFlags)
bool x_SetData (int iPos, int nValue)
int x_RemoveElem (int iPos)
MCD_STR x_GetElemContent (int iPos) const
bool x_SetElemContent (MCD_PCSZ szContent)
void x_DocChange (int nLeft, int nReplace, const MCD_STR &strInsert)
void x_Adjust (int iPos, int nShift, bool bAfterPos=false)
Static Protected Member Functions
static bool x_FindAny (MCD_PCSZ pDoc, int &nChar)
static bool x_FindName (TokenPos &token)
static MCD_STR x_GetToken (const TokenPos &token)
static MCD_STR x_EncodeCDATASection (MCD_PCSZ szData)
static bool x_FindAttrib (TokenPos &token, MCD_PCSZ pAttrib, int n=0)
static bool x_CreateNode (MCD_STR &strNode, int nNodeType, MCD_PCSZ pText)
static int x_ParseNode (TokenPos &token, NodePos &node)
static MCD_STR x_GetLastError ()
static int x_Hash (MCD_PCSZ p, int nSize)
static int x_GetEncodingCodePage (MCD_CSTR psz7Encoding)
static bool x_EndianSwapRequired (int nDocFlags)
static void x_EndianSwapUTF16 (unsigned short *pUTF16, int nCharLen)
static bool x_CanConvert (MCD_CSTR pszToEnc, MCD_CSTR pszFromEnc)
static int x_ConvertEncoding (ConvertEncoding &convert, void *pTo)
static bool x_Open (MCD_CSTR_FILENAME szFileName, FilePos &file)
static bool x_Read (void *pBuffer, FilePos &file)
static bool x_ReadText (MCD_STR &strDoc, FilePos &file)
static bool x_Write (void *pBuffer, FilePos &file, const void *pConstBuffer=NULL)
static bool x_WriteText (const MCD_STR &strDoc, FilePos &file)
static bool x_Close (FilePos &file)
static MCD_STR x_IntToStr (int n)
Protected Attributes
MCD_STR m_strDoc
MCD_STR m_strError
int m_iPosParent
int m_iPos
int m_iPosChild
int m_iPosFree
int m_iPosDeleted
int m_nNodeType
int m_nNodeOffset
int m_nNodeLength
int m_nDocFlags
SavedPosMapArray m_SavedPosMapArray
PosArray m_aPos
Classes
struct ConvertEncoding
struct ElemPos
struct FilePos
struct NodePos
struct NodeStack
struct PosArray
struct SavedPos
struct SavedPosMap
struct SavedPosMapArray
struct TokenPos
Member Enumeration Documentation
enum CMarkup::MarkupDocFlags
Enumerator:
MDF_UTF16LEFILE
MDF_UTF8PREAMBLE
MDF_IGNORECASE
MDF_READFILE
MDF_WRITEFILE
MDF_APPENDFILE
MDF_UTF16BEFILE
enum CMarkup::MarkupNodeFlags
Enumerator:
MNF_WITHCDATA
MNF_WITHNOLINES
MNF_WITHXHTMLSPACE
MNF_WITHREFS
MNF_WITHNOEND
MNF_ESCAPEQUOTES
MNF_NONENDED
MNF_ILLDATA
enum CMarkup::MarkupNodeType
Enumerator:
MNT_ELEMENT
MNT_TEXT
MNT_WHITESPACE
MNT_CDATA_SECTION
MNT_PROCESSING_INSTRUCTION
MNT_COMMENT
MNT_DOCUMENT_TYPE
MNT_EXCLUDE_WHITESPACE
MNT_LONE_END_TAG
MNT_NODE_ERROR
enum CMarkup::MarkupNodeFlagsInternal [protected]
Enumerator:
MNF_REPLACE
MNF_INSERT
MNF_CHILD
MNF_QUOTED
MNF_EMPTY
MNF_DELETED
MNF_FIRST
MNF_PUBLIC
MNF_ILLFORMED
MNF_USER
Constructor & Destructor Documentation
CMarkup::CMarkup () [inline]
References InitDocFlags(), and SetDoc().
CMarkup::CMarkup (MCD_CSTR szDoc) [inline]
References InitDocFlags(), and SetDoc().
CMarkup::CMarkup (int nFlags) [inline]
References m_nDocFlags, and SetDoc().
CMarkup::CMarkup (const CMarkup & markup) [inline]
CMarkup::~CMarkup () [inline]
Member Function Documentation
void CMarkup::operator= (const CMarkup & markup)
bool CMarkup::Load (MCD_CSTR_FILENAME szFileName)
bool CMarkup::SetDoc (MCD_PCSZ pDoc)
Referenced by CMarkup().
bool CMarkup::SetDoc (const MCD_STR & strDoc)
bool CMarkup::IsWellFormed ()
bool CMarkup::FindElem (MCD_CSTR szName = NULL)
bool CMarkup::FindChildElem (MCD_CSTR szName = NULL)
bool CMarkup::IntoElem ()
bool CMarkup::OutOfElem ()
void CMarkup::ResetChildPos () [inline]
References m_iPos, m_iPosParent, and x_SetPos().
void CMarkup::ResetMainPos () [inline]
References m_iPosParent, and x_SetPos().
void CMarkup::ResetPos () [inline]
References x_SetPos().
MCD_STR CMarkup::GetTagName () const
MCD_STR CMarkup::GetChildTagName () const [inline]
References m_iPosChild, and x_GetTagName().
MCD_STR CMarkup::GetData () const [inline]
References m_iPos, and x_GetData().
MCD_STR CMarkup::GetChildData () const [inline]
References m_iPosChild, and x_GetData().
MCD_STR CMarkup::GetElemContent () const [inline]
References m_iPos, and x_GetElemContent().
MCD_STR CMarkup::GetAttrib (MCD_CSTR szAttrib) const [inline]
References m_iPos, and x_GetAttrib().
MCD_STR CMarkup::GetChildAttrib (MCD_CSTR szAttrib) const [inline]
References m_iPosChild, and x_GetAttrib().
MCD_STR CMarkup::GetAttribName (int n) const
int CMarkup::FindNode (int nType = 0)
int CMarkup::GetNodeType () [inline]
References m_nNodeType.
bool CMarkup::SavePos (MCD_CSTR szPosName = MCD_T(""), int nMap = 0)
bool CMarkup::RestorePos (MCD_CSTR szPosName = MCD_T(""), int nMap = 0)
bool CMarkup::SetMapSize (int nSize, int nMap = 0)
const MCD_STR& CMarkup::GetError () const [inline]
References m_strError.
int CMarkup::GetDocFlags () const [inline]
References m_nDocFlags.
void CMarkup::SetDocFlags (int nFlags) [inline]
References m_nDocFlags.
bool CMarkup::Save (MCD_CSTR_FILENAME szFileName)
const MCD_STR& CMarkup::GetDoc () const [inline]
References m_strDoc.
bool CMarkup::AddElem (MCD_CSTR szName, MCD_CSTR szData = NULL, int nFlags = 0) [inline]
References x_AddElem().
bool CMarkup::InsertElem (MCD_CSTR szName, MCD_CSTR szData = NULL, int nFlags = 0) [inline]
References MNF_INSERT, and x_AddElem().
bool CMarkup::AddChildElem (MCD_CSTR szName, MCD_CSTR szData = NULL, int nFlags = 0) [inline]
References MNF_CHILD, and x_AddElem().
bool CMarkup::InsertChildElem (MCD_CSTR szName, MCD_CSTR szData = NULL, int nFlags = 0) [inline]
References MNF_CHILD, MNF_INSERT, and x_AddElem().
bool CMarkup::AddElem (MCD_CSTR szName, int nValue, int nFlags = 0) [inline]
References x_AddElem().
bool CMarkup::InsertElem (MCD_CSTR szName, int nValue, int nFlags = 0) [inline]
References MNF_INSERT, and x_AddElem().
bool CMarkup::AddChildElem (MCD_CSTR szName, int nValue, int nFlags = 0) [inline]
References MNF_CHILD, and x_AddElem().
bool CMarkup::InsertChildElem (MCD_CSTR szName, int nValue, int nFlags = 0) [inline]
References MNF_CHILD, MNF_INSERT, and x_AddElem().
bool CMarkup::AddAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue) [inline]
References m_iPos, and x_SetAttrib().
bool CMarkup::AddChildAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue) [inline]
References m_iPosChild, and x_SetAttrib().
bool CMarkup::AddAttrib (MCD_CSTR szAttrib, int nValue) [inline]
References m_iPos, and x_SetAttrib().
bool CMarkup::AddChildAttrib (MCD_CSTR szAttrib, int nValue) [inline]
References m_iPosChild, and x_SetAttrib().
bool CMarkup::AddSubDoc (MCD_CSTR szSubDoc) [inline]
References x_AddSubDoc().
bool CMarkup::InsertSubDoc (MCD_CSTR szSubDoc) [inline]
References MNF_INSERT, and x_AddSubDoc().
MCD_STR CMarkup::GetSubDoc () const [inline]
References m_iPos, and x_GetSubDoc().
bool CMarkup::AddChildSubDoc (MCD_CSTR szSubDoc) [inline]
References MNF_CHILD, and x_AddSubDoc().
bool CMarkup::InsertChildSubDoc (MCD_CSTR szSubDoc) [inline]
References MNF_CHILD, MNF_INSERT, and x_AddSubDoc().
MCD_STR CMarkup::GetChildSubDoc () const [inline]
References m_iPosChild, and x_GetSubDoc().
bool CMarkup::AddNode (int nType, MCD_CSTR szText) [inline]
References x_AddNode().
bool CMarkup::InsertNode (int nType, MCD_CSTR szText) [inline]
References MNF_INSERT, and x_AddNode().
bool CMarkup::RemoveElem ()
bool CMarkup::RemoveChildElem ()
bool CMarkup::RemoveNode ()
bool CMarkup::SetAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue, int nFlags = 0) [inline]
References m_iPos, and x_SetAttrib().
bool CMarkup::SetChildAttrib (MCD_CSTR szAttrib, MCD_CSTR szValue, int nFlags = 0) [inline]
References m_iPosChild, and x_SetAttrib().
bool CMarkup::SetAttrib (MCD_CSTR szAttrib, int nValue, int nFlags = 0) [inline]
References m_iPos, and x_SetAttrib().
bool CMarkup::SetChildAttrib (MCD_CSTR szAttrib, int nValue, int nFlags = 0) [inline]
References m_iPosChild, and x_SetAttrib().
bool CMarkup::SetData (MCD_CSTR szData, int nFlags = 0) [inline]
References m_iPos, and x_SetData().
bool CMarkup::SetChildData (MCD_CSTR szData, int nFlags = 0) [inline]
References m_iPosChild, and x_SetData().
bool CMarkup::SetData (int nValue) [inline]
References m_iPos, and x_SetData().
bool CMarkup::SetChildData (int nValue) [inline]
References m_iPosChild, and x_SetData().
bool CMarkup::SetElemContent (MCD_CSTR szContent) [inline]
References x_SetElemContent().
static bool CMarkup::ReadTextFile (MCD_CSTR_FILENAME szFileName, MCD_STR & strDoc, MCD_STR * pstrError = NULL, int * pnDocFlags = NULL, MCD_STR * pstrEncoding = NULL) [static]
static bool CMarkup::WriteTextFile (MCD_CSTR_FILENAME szFileName, const MCD_STR & strDoc, MCD_STR * pstrError = NULL, int * pnDocFlags = NULL, MCD_STR * pstrEncoding = NULL) [static]
static MCD_STR CMarkup::EscapeText (MCD_CSTR szText, int nFlags = 0) [static]
static MCD_STR CMarkup::UnescapeText (MCD_CSTR szText, int nTextLength = -1) [static]
static int CMarkup::UTF16To8 (char * pszUTF8, const unsigned short * pwszUTF16, int nUTF8Count) [static]
static int CMarkup::UTF8To16 (unsigned short * pwszUTF16, const char * pszUTF8, int nUTF8Count) [static]
static MCD_STR CMarkup::UTF8ToA (MCD_CSTR pszUTF8, int * pnFailed = NULL) [static]
static MCD_STR CMarkup::AToUTF8 (MCD_CSTR pszANSI) [static]
static void CMarkup::EncodeCharUTF8 (int nUChar, char * pszUTF8, int & nUTF8Len) [static]
static int CMarkup::DecodeCharUTF8 (const char *& pszUTF8, const char * pszUTF8End = NULL) [static]
static void CMarkup::EncodeCharUTF16 (int nUChar, unsigned short * pwszUTF16, int & nUTF16Len) [static]
static int CMarkup::DecodeCharUTF16 (const unsigned short *& pwszUTF16, const unsigned short * pszUTF16End = NULL) [static]
static bool CMarkup::DetectUTF8 (const char * pText, int nTextLen, int * pnNonASCII = NULL) [static]
static MCD_STR CMarkup::GetDeclaredEncoding (MCD_CSTR szDoc) [static]
void CMarkup::x_SetPos (int iPosParent, int iPos, int iPosChild) [inline, protected]
References m_iPos, m_iPosChild, m_iPosParent, m_nNodeLength, m_nNodeOffset, m_nNodeType, MARKUP_SETDEBUGSTATE, and MNT_ELEMENT.
Referenced by ResetChildPos(), ResetMainPos(), and ResetPos().
int CMarkup::x_GetFreePos () [inline, protected]
References CMarkup::PosArray::GetSize(), m_aPos, m_iPosFree, and x_AllocPosArray().
bool CMarkup::x_AllocPosArray (int nNewSize = 0) [protected]
Referenced by x_GetFreePos().
void CMarkup::InitDocFlags () [inline, protected]
References m_nDocFlags, and MDF_IGNORECASE.
Referenced by CMarkup().
bool CMarkup::x_ParseDoc () [protected]
int CMarkup::x_ParseElem (int iPos, TokenPos & token) [protected]
static bool CMarkup::x_FindAny (MCD_PCSZ pDoc, int & nChar) [static, protected]
static bool CMarkup::x_FindName (TokenPos & token) [static, protected]
static MCD_STR CMarkup::x_GetToken (const TokenPos & token) [static, protected]
int CMarkup::x_FindElem (int iPosParent, int iPos, MCD_PCSZ szPath) const [protected]
MCD_STR CMarkup::x_GetPath (int iPos) const [protected]
MCD_STR CMarkup::x_GetTagName (int iPos) const [protected]
Referenced by GetChildTagName().
MCD_STR CMarkup::x_GetData (int iPos) const [protected]
Referenced by GetChildData(), and GetData().
MCD_STR CMarkup::x_GetAttrib (int iPos, MCD_PCSZ pAttrib) const [protected]
Referenced by GetAttrib(), and GetChildAttrib().
static MCD_STR CMarkup::x_EncodeCDATASection (MCD_PCSZ szData) [static, protected]
bool CMarkup::x_AddElem (MCD_PCSZ pName, MCD_PCSZ pValue, int nFlags) [protected]
Referenced by AddChildElem(), AddElem(), InsertChildElem(), and InsertElem().
bool CMarkup::x_AddElem (MCD_PCSZ pName, int nValue, int nFlags) [protected]
MCD_STR CMarkup::x_GetSubDoc (int iPos) const [protected]
Referenced by GetChildSubDoc(), and GetSubDoc().
bool CMarkup::x_AddSubDoc (MCD_PCSZ pSubDoc, int nFlags) [protected]
Referenced by AddChildSubDoc(), AddSubDoc(), InsertChildSubDoc(), and InsertSubDoc().
static bool CMarkup::x_FindAttrib (TokenPos & token, MCD_PCSZ pAttrib, int n = 0) [static, protected]
bool CMarkup::x_SetAttrib (int iPos, MCD_PCSZ pAttrib, MCD_PCSZ pValue, int nFlags = 0) [protected]
Referenced by AddAttrib(), AddChildAttrib(), SetAttrib(), and SetChildAttrib().
bool CMarkup::x_SetAttrib (int iPos, MCD_PCSZ pAttrib, int nValue, int nFlags = 0) [protected]
bool CMarkup::x_AddNode (int nNodeType, MCD_PCSZ pText, int nNodeFlags) [protected]
Referenced by AddNode(), and InsertNode().
void CMarkup::x_RemoveNode (int iPosParent, int & iPos, int & nNodeType, int & nNodeOffset, int & nNodeLength) [protected]
void CMarkup::x_AdjustForNode (int iPosParent, int iPos, int nShift) [protected]
static bool CMarkup::x_CreateNode (MCD_STR & strNode, int nNodeType, MCD_PCSZ pText) [static, protected]
int CMarkup::x_InsertNew (int iPosParent, int & iPosRel, NodePos & node) [protected]
void CMarkup::x_LinkElem (int iPosParent, int iPosBefore, int iPos) [protected]
int CMarkup::x_UnlinkElem (int iPos) [protected]
int CMarkup::x_ReleaseSubDoc (int iPos) [protected]
int CMarkup::x_ReleasePos (int iPos) [protected]
bool CMarkup::x_GetMap (SavedPosMap *& pMap, int nMap, int nMapSize = 7) [protected]
void CMarkup::x_CheckSavedPos () [protected]
static int CMarkup::x_ParseNode (TokenPos & token, NodePos & node) [static, protected]
bool CMarkup::x_SetData (int iPos, MCD_PCSZ szData, int nFlags) [protected]
Referenced by SetChildData(), and SetData().
bool CMarkup::x_SetData (int iPos, int nValue) [protected]
int CMarkup::x_RemoveElem (int iPos) [protected]
MCD_STR CMarkup::x_GetElemContent (int iPos) const [protected]
Referenced by GetElemContent().
bool CMarkup::x_SetElemContent (MCD_PCSZ szContent) [protected]
Referenced by SetElemContent().
void CMarkup::x_DocChange (int nLeft, int nReplace, const MCD_STR & strInsert) [protected]
void CMarkup::x_Adjust (int iPos, int nShift, bool bAfterPos = false) [protected]
static MCD_STR CMarkup::x_GetLastError () [static, protected]
static int CMarkup::x_Hash (MCD_PCSZ p, int nSize) [inline, static, protected]
static int CMarkup::x_GetEncodingCodePage (MCD_CSTR psz7Encoding) [static, protected]
static bool CMarkup::x_EndianSwapRequired (int nDocFlags) [static, protected]
static void CMarkup::x_EndianSwapUTF16 (unsigned short * pUTF16, int nCharLen) [static, protected]
static bool CMarkup::x_CanConvert (MCD_CSTR pszToEnc, MCD_CSTR pszFromEnc) [static, protected]
static int CMarkup::x_ConvertEncoding (ConvertEncoding & convert, void * pTo) [static, protected]
static bool CMarkup::x_Open (MCD_CSTR_FILENAME szFileName, FilePos & file) [static, protected]
static bool CMarkup::x_Read (void * pBuffer, FilePos & file) [static, protected]
static bool CMarkup::x_ReadText (MCD_STR & strDoc, FilePos & file) [static, protected]
static bool CMarkup::x_Write (void * pBuffer, FilePos & file, const void * pConstBuffer = NULL) [static, protected]
static bool CMarkup::x_WriteText (const MCD_STR & strDoc, FilePos & file) [static, protected]
static bool CMarkup::x_Close (FilePos & file) [static, protected]
static MCD_STR CMarkup::x_IntToStr (int n) [inline, static, protected]
References MCD_CHAR, MCD_SPRINTF, MCD_SSZ, MCD_STR, and MCD_T.
Member Data Documentation
MCD_STR CMarkup::m_strDoc [protected]
Referenced by GetDoc().
MCD_STR CMarkup::m_strError [protected]
Referenced by GetError().
int CMarkup::m_iPosParent [protected]
Referenced by ResetChildPos(), ResetMainPos(), and x_SetPos().
int CMarkup::m_iPos [protected]
Referenced by AddAttrib(), GetAttrib(), GetData(), GetElemContent(), GetSubDoc(), ResetChildPos(), SetAttrib(), SetData(), and x_SetPos().
int CMarkup::m_iPosChild [protected]
Referenced by AddChildAttrib(), GetChildAttrib(), GetChildData(), GetChildSubDoc(), GetChildTagName(), SetChildAttrib(), SetChildData(), and x_SetPos().
int CMarkup::m_iPosFree [protected]
Referenced by x_GetFreePos().
int CMarkup::m_iPosDeleted [protected]
int CMarkup::m_nNodeType [protected]
Referenced by GetNodeType(), and x_SetPos().
int CMarkup::m_nNodeOffset [protected]
Referenced by x_SetPos().
int CMarkup::m_nNodeLength [protected]
Referenced by x_SetPos().
int CMarkup::m_nDocFlags [protected]
Referenced by CMarkup(), GetDocFlags(), InitDocFlags(), and SetDocFlags().
SavedPosMapArray CMarkup::m_SavedPosMapArray [protected]
PosArray CMarkup::m_aPos [protected]
Referenced by x_GetFreePos().
The documentation for this class was generated from the following file:
Markup.h