Neural++: CMarkup::ElemPos Struct Reference
CMarkup::ElemPos Struct Reference
#include <Markup.h>
Public Member Functions
ElemPos ()
ElemPos (const ElemPos &pos)
int StartTagLen () const
void SetStartTagLen (int n)
void AdjustStartTagLen (int n)
int EndTagLen () const
void SetEndTagLen (int n)
bool IsEmptyElement ()
int StartContent () const
int ContentLen () const
int StartAfter () const
int Level () const
void SetLevel (int nLev)
void ClearVirtualParent ()
Public Attributes
int nStart
int nLength
unsigned int nStartTagLen: 22
unsigned int nEndTagLen: 10
int nFlags
int iElemParent
int iElemChild
int iElemNext
int iElemPrev
Constructor & Destructor Documentation
CMarkup::ElemPos::ElemPos () [inline]
CMarkup::ElemPos::ElemPos (const ElemPos & pos) [inline]
Member Function Documentation
int CMarkup::ElemPos::StartTagLen () const [inline]
References nStartTagLen.
Referenced by ContentLen(), IsEmptyElement(), and StartContent().
void CMarkup::ElemPos::SetStartTagLen (int n) [inline]
References nStartTagLen.
void CMarkup::ElemPos::AdjustStartTagLen (int n) [inline]
References nStartTagLen.
int CMarkup::ElemPos::EndTagLen () const [inline]
References nEndTagLen.
Referenced by ContentLen().
void CMarkup::ElemPos::SetEndTagLen (int n) [inline]
References nEndTagLen.
bool CMarkup::ElemPos::IsEmptyElement () [inline]
References nLength, and StartTagLen().
int CMarkup::ElemPos::StartContent () const [inline]
References nStart, and StartTagLen().
int CMarkup::ElemPos::ContentLen () const [inline]
References EndTagLen(), nLength, and StartTagLen().
int CMarkup::ElemPos::StartAfter () const [inline]
References nLength, and nStart.
int CMarkup::ElemPos::Level () const [inline]
References nFlags.
void CMarkup::ElemPos::SetLevel (int nLev) [inline]
References nFlags.
void CMarkup::ElemPos::ClearVirtualParent () [inline]
Member Data Documentation
int CMarkup::ElemPos::nStart
Referenced by StartAfter(), and StartContent().
int CMarkup::ElemPos::nLength
Referenced by ContentLen(), IsEmptyElement(), and StartAfter().
unsigned int CMarkup::ElemPos::nStartTagLen
Referenced by AdjustStartTagLen(), SetStartTagLen(), and StartTagLen().
unsigned int CMarkup::ElemPos::nEndTagLen
Referenced by EndTagLen(), and SetEndTagLen().
int CMarkup::ElemPos::nFlags
Referenced by Level(), and SetLevel().
int CMarkup::ElemPos::iElemParent
int CMarkup::ElemPos::iElemChild
int CMarkup::ElemPos::iElemNext
int CMarkup::ElemPos::iElemPrev
The documentation for this struct was generated from the following file:
Markup.h