Neural++: CMarkup::PosArray Struct Reference
CMarkup::PosArray Struct Reference
#include <Markup.h>
Public Types
enum { PA_SEGBITS = 16, PA_SEGMASK = 0xffff }
Public Member Functions
PosArray ()
~PosArray ()
void RemoveAll ()
void Release ()
void Clear ()
int GetSize () const
int SegsUsed () const
ElemPos & operator[] (int n) const
Public Attributes
ElemPos ** pSegs
int nSize
int nSegs
Member Enumeration Documentation
anonymous enum
Enumerator:
PA_SEGBITS
PA_SEGMASK
Constructor & Destructor Documentation
CMarkup::PosArray::PosArray () [inline]
References Clear().
CMarkup::PosArray::~PosArray () [inline]
References Release().
Member Function Documentation
void CMarkup::PosArray::RemoveAll () [inline]
References Clear(), and Release().
void CMarkup::PosArray::Release () [inline]
References pSegs, and SegsUsed().
Referenced by RemoveAll(), and ~PosArray().
void CMarkup::PosArray::Clear () [inline]
References nSegs, nSize, and pSegs.
Referenced by PosArray(), and RemoveAll().
int CMarkup::PosArray::GetSize () const [inline]
References nSize.
Referenced by CMarkup::x_GetFreePos().
int CMarkup::PosArray::SegsUsed () const [inline]
References nSize, and PA_SEGBITS.
Referenced by Release().
ElemPos& CMarkup::PosArray::operator[] (int n) const [inline]
Member Data Documentation
ElemPos** CMarkup::PosArray::pSegs
Referenced by Clear(), and Release().
int CMarkup::PosArray::nSize
Referenced by Clear(), GetSize(), and SegsUsed().
int CMarkup::PosArray::nSegs
Referenced by Clear().
The documentation for this struct was generated from the following file:
Markup.h